### ISSUE TITLE
touch based vertical scrolling is broken

### ISSUE THREAD

**Issue by evilsocket** [bettercap/hydra#3]
for some reason, at least on iOS, tables can't be scrolled vertically with a touch

**Comment by yungtravla** [comment]
I think this may be related to multiple scrollable viewports:

![image](https://user-images.githubusercontent.com/29265684/54410241-4dc3e280-4736-11e9-9f86-0430c299a9db.png)

As you can see, on the far right and bottom of the page, there's more than 1 scrollbar. I think that the bug you experienced might be that your browser thought you were trying to scroll a different viewport.

I am still getting my head around the structure of hydra before I can send PRs, but I think `overflow: none` might do the trick here :)

**Comment by yungtravla** [comment]
This PR https://github.com/bettercap/hydra/pull/4 removes the unused scrollbars, and may or may not fix this issue as well

**Comment by evilsocket** [comment]
closed with https://github.com/bettercap/hydra/pull/4 <3
