### ISSUE TITLE
Unauthorized access despite having introduced right credentials

### ISSUE THREAD

**Issue by q2dg** [bettercap/hydra#7]
Hello.

I've setup Hydra as Readme says, with "pepe" user and "1234 password. But when I want to log in, a red ballon appears with the message "Unkown error".

Looking at Bettercap console I can see the message "Unauthorized authentication attempt from xxxx"

Looking at "Developer tools" in my Firefox client I can see offending request gives an 401 error, has the method OPTIONS and want to go to http://bettercapIp:8081/api/session url.

Thanks

PD: I've seen https://github.com/bettercap/hydra/issues/2 . i've just opened this issue for reference

**Comment by evilsocket** [comment]
this software is still under heavy developement
